# ---------------------------------------------------------------------------
#
#   Author
#     - luncliff@gmail.com
#
# ---------------------------------------------------------------------------
sudo: false

git:
  submodules: true
  depth: 5

notifications:
  email:
    - luncliff@gmail.com

language: android

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - tree
      - unzip
      - ninja-build
      - cmake

android:
  components:
    - tools
    - platform-tools
    - android-27
    - android-28
    - build-tools-28.0.3
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

install:
  # Android NDK
  - yes | sdkmanager --update > /dev/null 2>&1;
  - sdkmanager ndk-bundle > /dev/null 2>&1;
  # Gradle from https://sdkman.io/
  - curl -s "https://get.sdkman.io" | bash > /dev/null
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk version
  - sdk install gradle 5.1.1
  - sdk use gradle

before_script:
  - gradle --version

script:
  - gradle clean
  - gradle assemble

after_success:
  - tree ./install

matrix: 
  include:
    - name: "Android"
